---
- hosts: theone
  gather_facts: true
  tasks:
    # Maximum Memory Maps Configuration
    - name: Maximum Memory Maps Configuration
      block:
        - sysctl:
            name: vm.swappiness
            value: 1
            state: present

    - name: Keepalive related parameters
      block:
        - sysctl:
            name: net.ipv4.tcp_keepalive_intvl
            value: 60
            state: present

        - sysctl:
            name: net.ipv4.tcp_keepalive_probes
            value: 20
            state: present

        - sysctl:
            name: net.ipv4.tcp_keepalive_time
            value: 600
            state: present
